CREATE TABLE IF NOT EXISTS book (
    book_id CHAR(36) PRIMARY KEY COMMENT '書籍ID',
    title VARCHAR(255) NOT NULL COMMENT 'タイトル',
    summary TEXT NOT NULL COMMENT '書籍要約',
    author VARCHAR(255) NOT NULL COMMENT '著者',
    price INT UNSIGNED NOT NULL COMMENT '価格',
    publication_date DATE NOT NULL COMMENT '発刊日',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時'
);
