// Code generated by reverse. DO NOT EDIT.

package gen

{{$table := index .Tables 0}}
{{$structName := TableMapper $table.Name}}
{{$hasCreatedAt := false}}
{{$hasUpdatedAt := false}}

{{range $table.ColumnsSeq -}}
	{{$column := $table.GetColumn . -}}
	{{if eq $column.Name "created_at" -}}
		{{$hasCreatedAt = true -}}
	{{end -}}
	{{if eq $column.Name "updated_at" -}}
		{{$hasUpdatedAt = true -}}
	{{end -}}
{{end}}

import (
{{- if and $hasCreatedAt $hasUpdatedAt }}
	"context"
{{- end }}
{{- range .Imports }}
	"{{.}}"
{{- end }}

	"github.com/uptrace/bun"
)

const (
	{{$structName}}TableName = "{{$table.Name}}"

{{- range $table.ColumnsSeq }}
	{{$column := $table.GetColumn .}}
	{{$structName}}Column{{ColumnMapper $column.Name}} = "{{$column.Name}}"
{{- end }}
)

type {{$structName}} struct {
	bun.BaseModel `bun:"table:{{$table.Name}}"`

{{range $table.ColumnsSeq}}
{{$column := $table.GetColumn . -}}
{{$tag := $column.Name -}}

{{if $column.IsPrimaryKey -}}
	{{$tag = printf "%s,pk" $tag -}}
{{end -}}

{{if $column.IsAutoIncrement -}}
	{{$tag = printf "%s,autoincrement" $tag -}}
{{end -}}

{{if not $column.Nullable -}}
	{{$tag = printf "%s,notnull" $tag -}}
{{end -}}

{{if $column.Comment}}
	// {{$column.Comment}}
{{end -}}
	{{ColumnMapper $column.Name}} {{Type $column}} `bun:"{{$tag}}"`
{{end}}
}

{{if and $hasCreatedAt $hasUpdatedAt}}
var _ bun.BeforeAppendModelHook = (*{{$structName}})(nil)

func (m *{{$structName}}) BeforeAppendModel(
	_ context.Context,
	query bun.Query,
) error {
	now := time.Now().UTC()

	switch query.(type) {
	case *bun.InsertQuery:
		if m.CreatedAt.IsZero() {
			m.CreatedAt = now
		}
		if m.UpdatedAt.IsZero() {
			m.UpdatedAt = now
		}

	case *bun.UpdateQuery:
		m.UpdatedAt = now
	}

	return nil
}
{{end}}
